### PR TITLE
#18: Remove geophp dependency and add geofield

### PR DESCRIPTION
**Pull request by laryn**

### CODE REVIEW

**Comment by laryn** [comment]
Thanks for verifying @keiserjb -- what do you think of it @jenlampton ?

**Comment by jenlampton** [comment]
Does geofield depend on geophp? Or is the geophp library bundled in geofield now? I forget how this all fits together...

If the library is in geofield now, then it would make more sense to depend on geofield, since people usually use geofield and geocoder together anyway.

**Comment by laryn** [comment]
@jenlampton It looks like `geophp` is now bundled in `geofield`: https://github.com/backdrop-contrib/geofield/commit/0a3837f4f91ddccd342bd393691d760d32fc9658

**Comment by jenlampton** [comment]
great, let's do it :)

**Comment by laryn** [comment]
@jenlampton If the PR looks good I will leave the merging to you as a maintainer. ;)

**Comment by jenlampton** [comment]
Looks great!

**Pull request merged**
